"""initial schema

Revision ID: e23def1eac8a
Revises: 
Create Date: 2026-02-25 13:37:21.012212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23def1eac8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_content_attempt', ['user_id', 'content_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_content_attempt', type_='unique')

    # ### end Alembic commands ###
